accounts/urls.py
from django.urls import path, reverse_lazy, re_path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'accounts'

urlpatterns = [
    path('password/change/', auth_views.PasswordChangeView.as_view(
        success_url=reverse_lazy('accounts:password_change_done'),
        template_name='accounts/password_change_form.html',
    ),
        name='password_change'),
    path('password/change/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='accounts/password_change_done.html',
    ), name='password_change_done'),
    path('password/reset/complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='accounts/password_reset_complete.html'
    ),
         name='password_reset_complete'),
    re_path(r'^password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,40})/$',
            auth_views.PasswordResetConfirmView.as_view(
                template_name='accounts/password_reset_confirm.html',
                success_url=reverse_lazy('accounts:password_reset_complete')
            ),
            name='password_reset_confirm'),
    path('password/reset/', auth_views.PasswordResetView.as_view(
        email_template_name='accounts/password_reset_email.html',
        subject_template_name='accounts/password_reset_subject.txt',
        success_url=reverse_lazy('accounts:password_reset_done'),
        template_name='accounts/password_reset_form.html',
    ), name='password_reset'),
    path('password/reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='accounts/password_reset_done.html'
    ), name='password_reset_done'),

    path('settings/password/', views.password, name='password'),

    path('signup/', views.signup_view, name="signup"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout")
]

articles/urls.py
from django.urls import path, re_path
from . import views

app_name = 'articles'

urlpatterns = [
    path('liking', views.liking, name='liking'),
    path('add_to_view', views.add_to_view, name='add-to-view'),
    path('add_to_favourite', views.add_to_favourite, name='liking'),
    path('favourite-articles', views.favourite_articles, name='favourite-articles'),
    path('report-to-comment', views.report_to_comment, name='report-to-comment'),
    path('report-to-article', views.report_to_article, name='report-to-article'),
    path('follow-to-categories', views.following_to_category, name='follow-to-categories'),
    path('follow-to-users', views.following_to_user, name='follow-to-users'),
    path('', views.article_list, name="list"),
    path('following/', views.list_by_following, name="list-by-following"),
    path('top/', views.list_by_top, name="list-by-top"),
    path('categories/', views.category_list, name="category-list"),
    path('category/<str:slug>', views.articles_by_category, name="articles-by-category"),
    path('new', views.article_create, name="create"),
    re_path('delete-comment/(?P<pk>\\d+)', views.delete_comment, name='delete-comment'),
    re_path('add-comment/(?P<pk>\\d+)', views.add_comment, name='add-comment'),
    re_path('(?P<slug>[\\w-]+)/edit', views.article_edit, name='edit'),
    re_path('(?P<slug>[\\w-]+)/delete', views.article_delete, name='delete'),
    re_path('(?P<slug>[\\w-]+)/$', views.article_detail, name='detail')
]

blogger/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include, re_path
from articles import views as article_views
from accounts import views as accounts_views
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('oauth/', include('social_django.urls', namespace='social')),
    re_path(r'^markdownx/', include('markdownx.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
    re_path('^tags/(?P<tag>[\\w-]+)', article_views.articles_by_tag, name='articles-by-tag'),
    path('', article_views.article_list, name="home"),
    re_path(r'^@(?P<username>.+)$', views.username_detail, name='users-profile'),
    path('profile/', include('profiles.urls')),
    path('search/tags/', article_views.article_tag_search, name='search-tag'),
    path('search/users/', accounts_views.users_search, name='search-users'),
    path('search/', article_views.article_search, name='search'),
)

profiles/urls.py
from django.urls import path, re_path
from . import views

app_name = 'profiles'

urlpatterns = [
    path('', views.profile_detail, name='profile-details'),
    # path('edit', views.update_profile, name='profile-update'),
    path('articles/draft', views.draft_articles, name='draft-articles'),
    path('articles/published', views.published_articles, name='published-articles'),
    path('set-avatar/', views.set_avatar, name='set-avatar')
]

templates/_partials/_article_item_minimal.html
<article class="row mt-2 d-flex">
    <div class="col ml-3 mr-auto">
        <h4 class="entry-title mb-1">
            <a href="{% url 'articles:detail' slug=article.slug %}">{{ article.title|capfirst }}</a>
        </h4>
        <div class="entry-excerpt">
            <p class="mb-2 mt-2">
                {{ article.snippet_large }}
            </p>
        </div>
        <div class="entry-meta align-items-center">
            {% if article.created_at|date == article.updated_at|date %}
                <span>Created: {{ article.created_at|date:'d.m.y H:i' }}</span>
            {% else %}
                <span>Updated: {{ article.updated_at|date:'d.m.y H:i' }}</span>
            {% endif %}
            <span class="middotDivider"></span>
            <span class="readingTime" title="{{ article.time_of_read }} read">{{ article.time_of_read }} read</span>
        </div>
    </div>
    {% if user.username|lower == article.author.username|lower %}
        <div class="ml-auto mt-auto mb-auto mr-3 d-flex flex-column">
            <form action="{% url 'articles:edit' article.slug %}" class="m-1">
                <button type="submit" class="btn btn-info w-100 m-auto">Edit</button>
            </form>
            <form method="get" action="{% url 'articles:delete' article.slug %}" class="m-1">
                <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal">
                    Delete
                </button>
                <div class="modal" id="deleteModal">
                    <div class="modal-dialog modal-dialog-centered modal-sm ">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h4 class="modal-title">Delete</h4>
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                            </div>
                            <div class="modal-body">
                                Are you sure to delete the article?
                            </div>
                            <div class="modal-footer">
                                <button type="submit" class="btn btn-danger">
                                    Yes
                                </button>
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">
                                    No
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    {% endif %}

</article>
<hr>

templates/_partials/_category_item.html
{% load categories %}
<article class="row mt-2 d-flex">
    <div class="col ml-3 mr-auto">
        <h4 class="entry-title mb-1">
            <a href="{% url 'articles:articles-by-category' category.slug %}">{{ category.title|capfirst }}</a>
        </h4>
        <div class="entry-excerpt">
            <p class="mb-2 mt-2">
                {{ category.description }}
            </p>
        </div>
        <div class="entry-meta align-items-center">
            {{ category.get_count_articles }}
            <span class="middotDivider">articles</span>
        </div>
    </div>
    <div class="ml-auto mt-auto mb-auto mr-3 d-flex flex-column">
        <form action="{% url 'articles:follow-to-categories' %}" method="post" class="m-1">
            {% csrf_token %}
            <input type="hidden" name="category_id" value="{{ category.id }}">
            {% is_followed category.id user.id as is_follow %}
            {% if not is_follow %}
                <input type="hidden" name="what" value="follow">
                <button type="submit" class="btn btn-primary w-100 m-auto">Follow</button>
            {% else %}
                <input type="hidden" name="what" value="unfollow">
                <button type="submit" class="btn btn-danger w-100 m-auto">UnFollow</button>
            {% endif %}
        </form>
    </div>
</article>
<hr>

templates/_partials/_comment_item.html
{% load static %}
<div class="comment row-flex mx-auto my-3" id="comment-{{ forloop.parentloop.counter }}{{ forloop.counter }}">

    <div class="p-0 w-100">
        <div class="{% if article.author.username|lower == comment.author.username|lower %} bg-lightblue {% endif %} d-flex align-items-center">
            <a class="author-avatar mx-1" href="{% url 'users-profile' comment.author %}">
                <img class="avatar"
                     src="{% if comment.author.profile.avatar %} {{ comment.author.profile.avatar.url }} {% else %} {% static 'images/default-avatar.jpg' %} {% endif %}"
                     alt="img">
            </a>
            <a href="{% url 'users-profile' comment.author %}" class="text-author ml-1">
                <h5 class="font-weight-bold" id="author_name">{{ comment.author }}</h5>
            </a>
            <span class="datetime small text-secondary ml-auto mr-1">{{ comment.created_on|date:'d.n.y H:i' }}</span>
        <i class="icon-attention cursor-pointer" data-toggle="modal" data-target="#report_comment-{{ comment.id }}" title="Report"></i>
            {% include '_partials/_modal_report.html' with id_modal=comment.id reports=comment_reports %}
        </div>
        <div class="my-1 px-1" id="{{ comment.id }}">
            {% if comment.status|lower == "active" %}
                {{ comment.content|capfirst }}
            {% else %}
                This comment deleted by Author
            {% endif %}
        </div>
        <div class="d-flex align-items-end">
            <a href="#comment-{{ forloop.parentloop.counter }}{{ forloop.counter }}" class="text-muted small mx-2"
               onclick="replying(`{{ forloop.parentloop.counter }}{{ forloop.counter }}`, {{ forloop.parentloop.counter }})">Reply</a>
            {% if user.username|lower == comment.author.username|lower and comment.status|lower == 'active' %}
                <a class="text-muted small" data-toggle="modal"
                   data-target="#deleteCommit--{{ forloop.parentloop.counter }}{{ forloop.counter }}">Delete</a>
            {% endif %}
        </div>
        <div class="modal" id="deleteCommit--{{ forloop.parentloop.counter }}{{ forloop.counter }}">
            <div class="modal-dialog modal-dialog-centered modal-sm">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">Delete</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body">
                        Are you sure to delete the commit?
                    </div>
                    <div class="modal-footer">
                        <a href="{% url 'articles:delete-comment' comment.id %}" class="btn btn-outline-danger">
                            Yes
                        </a>
                        <a class="btn btn-outline-secondary" data-dismiss="modal">
                            No
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div id="reply-comment-{{ forloop.parentloop.counter }}{{ forloop.counter }}"></div>
    </div>
</div>

templates/_partials/_modal_report.html
<div class="modal fade" id="report_comment-{{ id_modal }}" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <form>
                {% csrf_token %}
                <div class="modal-header">
                    <h5 class="modal-title">Report to Comment</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-check">
                        {% for report in reports %}
                            <div class="item-radio">
                                <label class="form-check-label" for="{{ report.0 }}">{{ report.1 }}</label>
                                <input type="radio" name="report-to-comment" class="form-check-input"
                                       value="{{ report.0 }}">
                            </div>
                        {% endfor %}
                        <textarea style="font-size: 12px" minlength="20px" name="comment_of_report" placeholder="Extra comment to report..."></textarea>
                        <input type="hidden" name="comment_id" value="{{ comment.id }}">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-danger" onclick="ReportToComment(event, '{{ comment.id }}')">Report</button>
                </div>
            </form>
        </div>
    </div>
</div>

templates/_partials/_modal_report_article.html
<div class="modal fade" id="report_article-{{ id_modal }}" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <form>
                {% csrf_token %}
                <div class="modal-header">
                    <h5 class="modal-title">Report to article</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-check">
                        {% for report in reports %}
                            <div class="item-radio">
                                <label class="form-check-label" for="{{ report.0 }}">{{ report.1 }}</label>
                                <input type="radio" name="report-to-article" class="form-check-input"
                                       value="{{ report.0 }}">
                            </div>
                        {% endfor %}
                        <textarea style="font-size: 12px" minlength="20px" name="comment_of_report" placeholder="Extra comment to report..."></textarea>
                        <input type="hidden" name="article_id" value="{{ article.id }}">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-danger" onclick="ReportToArticle(event, '{{ article.id }}')">Report</button>
                </div>
            </form>
        </div>
    </div>
</div>

templates/_partials/_user_item.html
<a href="{% url 'users-profile' user.username %}">
    {{ user }}
</a>
<br>
<hr>

templates/_partials/article_author.html
<div class="box box-author m_b_1rem">
    <div class="post-author row-flex">
        <div class="author-img">
            <img alt="author avatar" src="/static/images/author-avata-1.jpg" class="avatar">
        </div>
        <div class="author-content">
        <div class="top-author">
            <h5 class="heading-font"><a href="author.html" title="Ryan" rel="author">Ryan Mark</a> Subscribe+ </h5></div>
            <p class="d-none d-md-block">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse laoreet ut ligula et semper. Aenean consectetur, est id gravida venenatis.</p>
            <div class="content-social-author">
                <a target="_blank" class="author-social" href="#">Facebook </a>
                <a target="_blank" class="author-social" href="#">Twitter </a>
                <a target="_blank" class="author-social" href="#"> Google + </a>
            </div>
        </div>
    </div>
</div>

templates/_partials/categories.html
{% load categories %}
<nav id="main-menu" class="stick d-lg-block d-none">
    <div class="container">
        <div class="menu-primary">
            <ul>
                <li class="current-menu-item"><a href="{% url 'home' %}">Home</a></li>
                <li class="menu-item-has-children"><a href="{% url 'articles:category-list'%}">Categories</a>
                    <ul class="sub-menu">
                        {% get_active_categories as categories %}
                        {% for category in categories %}
                            <li>
                                <a href="{% url 'articles:articles-by-category' category.slug %}">{{ category.title|capfirst }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </li>
                <li><a href="typography.html">Typography</a></li>
                <li><a href="categories.html">Politics</a></li>
                <li><a href="categories.html">Health</a></li>
                <li><a href="categories.html">Design</a></li>
                <li><a href="categories.html">Startups</a></li>
                <li><a href="categories.html">Culture</a></li>
                <li><a href="contact.html">Contact</a></li>
                <li class="menu-item-has-children"><a href="#">More...</a>
                    <ul class="sub-menu">
                        <li><a href="search.html">Search</a></li>
                        <li><a href="author.html">Author</a></li>
                        <li><a href="404.html">404</a></li>
                    </ul>
                </li>
            </ul>
            <span></span>
        </div>
    </div>
</nav>

templates/_partials/comment.html
<div class="single-comment comments_wrap">
    <section id="comments">
        <div class="comments-inner clr">
            <div id="respond" class="comment-respond">
                <h5 id="reply-title" class="comment-reply-title">Leave a Reply</h5>
                <form action="{% url 'articles:add-comment' article.id %}" method="post" id="commentform" class="comment-form">
                    {% csrf_token %}
                    <p class="comment-notes">
                        <span id="email-notes">
                            {% if form_comment.content.errors.items %}
                                {{ form_comment.content.errors }}
                            {% endif %}
                        </span>
                    </p>
                    <p class="comment-form-comment">
                        {{ form_comment.content }}

                    </p>
                    <p class="form-submit">
                        <input name="submit" type="submit" id="submit" class="btn btn-success btn-block"
                               value="Post Comment">
                    </p>
                </form>
            </div>
            <!-- #respond -->
        </div>
    </section>
</div>

templates/_partials/footer.html
<footer class="mt-5">
    <div class="container">
        <div class="divider"></div>
        <div class="row">
            <div class="col-md-6 copyright text-xs-center">
                <p>Copyright © 2019 Merinda inc. Designed by <a href="https://alithemes.com">AliThemes.com</a></p>
            </div>
            <div class="col-md-6">
                <ul class="social-network inline text-md-right text-sm-center">
                    <li class="list-inline-item"><a href="#"><i class="icon-facebook"></i></a></li>
                    <li class="list-inline-item"><a href="#"><i class="icon-twitter"></i></a></li>
                    <li class="list-inline-item"><a href="#"><i class="icon-behance"></i></a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>

templates/_partials/header.html
{% load static i18n %}
<div class="container">
    <div class="align-items-center w-100">
        <h1 class="logo float-left navbar-brand"><a href="/" class="logo">Merinda</a></h1>
        <form action="{% url 'set_language' %}" method="post" class="form-group float-left" id="form-language">
            {% csrf_token %}
            <input name="next" type="hidden" value="{{ redirect_to }}">
            <select name="language" class="custom-select ml-5 mr-n5 mt-n1 border-0" onchange="$('#form-language').submit()">
                {% get_current_language as LANGUAGE_CODE %}
                {% get_available_languages as LANGUAGES %}
                {% get_language_info_list for LANGUAGES as languages %}
                {% for language in languages %}
                    <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %}
                            selected{% endif %}>
                        {{ language.name_local|capfirst }}
                    </option>
                {% endfor %}
            </select>
        </form>
        <div class="header-right float-right w-50">
            <div class="d-flex float-right text-right align-items-center">
                <form action="{% url 'search' %}" method="get" class="search-form d-flex align-items-center">
                    <a href="javascript:void(0)" class="searh-toggle">
                        <i class="icon-search"></i>
                    </a>
                    <input type="text" class="search_field" placeholder="Search..." value="" name="q">
                </form>
                {% if user.is_authenticated %}
                    <ul class="top-menu heading nav w-100 d-lg-flex align-items-center">
                        <li><a href="{% url 'articles:create' %}" class="btn pt-1 pb-1">New Article</a></li>
                        <li>
                            <div class="author-avatar dropdown">
                                <img title="@{{ user.username }}" class="dropdown-toggle cursor-pointer"
                                     data-toggle="dropdown"
                                     aria-haspopup="true" aria-expanded="false"
                                     src="{% if user.profile.avatar %} {{ user.profile.avatar.url }} {% else %} {% static 'images/default-avatar.jpg' %} {% endif %}"
                                     alt="img">
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" href="{% url 'profiles:profile-details' %}"><i
                                            class="icon-user"></i>Profile</a>
                                    <a class="dropdown-item" href="{% url 'profiles:draft-articles' %}"><i
                                            class="icon-pencil"></i>My articles</a>
                                    <a class="dropdown-item" href="{% url 'articles:favourite-articles' %}"><i
                                            class="icon-bookmark"></i>Saved articles</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item logout-link" href="{% url 'accounts:logout' %}"><i
                                            class="icon-logout"></i>Log out</a>
                                </div>
                            </div>
                        </li>
                    </ul>
                {% else %}
                    <ul class="top-menu heading nav w-100 d-lg-flex d-flex align-items-center">
                        <li>
                            <form action="{% url 'accounts:login' %}">
                                <input type="hidden" name="next" value="{{ request.get_full_path }}">
                                <button type="submit" class="btn-green px-sm-1">Login</button>
                            </form>
                        </li>

                        <li>
                            <form action="{% url 'accounts:signup' %}">
                                <input type="hidden" name="next" value="{{ request.get_full_path }}">
                                <button type="submit" class="btn-green ml-2 px-sm-1">Signup</button>
                            </form>
                        </li>
                    </ul>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
</div>

templates/_partials/pagination.html
<div>
    <ul class="page-numbers heading">
        {% if articles.has_previous %}
            <li><a href="?page={{ articles.previous_page_number }}" class="active icon-left-open-big"></a></li>
        {% endif %}
        {% if articles.number > 6 %}
            <li><a href="?page={{ articles.number|add:-6 }}" class="page-numbers">...</a></li>
        {% endif %}
        {% for i in articles.paginator.page_range %}
            {% if articles.number == i %}
                <li class="active page-numbers current" aria-current="page"><span>{{ i }}</span></li>
            {% endif %}
            {% if i <= articles.number|add:5 and i >= articles.number|add:-5 and i != articles.number %}
                <li><a class="page-numbers" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>
            {% endif %}
        {% endfor %}
        {% if articles.paginator.num_pages > articles.number|add:5 %}
            <li><a href="?page={{ articles.number|add:6 }}" class="page-numbers">...</a></li>
        {% endif %}
        {% if articles.has_next %}
            <li><a href="?page={{ articles.next_page_number }}" class="active icon-right-open-big"></a></li>
        {% endif %}
    </ul>
</div>

templates/_partials/subscribe.html
<div class="border p-5 bg-lightblue mb-5">
    <div class="row justify-content-between">
        <div class="col-md-5 mb-2 mb-md-0">
            <h5 class="font-weight-bold secondfont mb-3 mt-0">Become a member</h5>
            <p class="small-text">Get the latest news right in your inbox. We never spam!</p>
        </div>
        <div class="col-md-7">
            <div class="row">
                <div class="col-md-12">
                    <input type="text" class="form-control" placeholder="Enter your e-mail address">
                </div>
                <div class="col-md-12 mt-2">
                    <button type="submit" class="btn btn-success btn-block">Subscribe</button>
                </div>
            </div>
        </div>
    </div>
</div>