accounts/urls.py
from django.urls import path, reverse_lazy, re_path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'accounts'

urlpatterns = [
    path('password/change/', auth_views.PasswordChangeView.as_view(
        success_url=reverse_lazy('accounts:password_change_done'),
        template_name='accounts/password_change_form.html',
    ),
        name='password_change'),
    path('password/change/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='accounts/password_change_done.html',
    ), name='password_change_done'),
    path('password/reset/complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='accounts/password_reset_complete.html'
    ),
         name='password_reset_complete'),
    re_path(r'^password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,40})/$',
            auth_views.PasswordResetConfirmView.as_view(
                template_name='accounts/password_reset_confirm.html',
                success_url=reverse_lazy('accounts:password_reset_complete')
            ),
            name='password_reset_confirm'),
    path('password/reset/', auth_views.PasswordResetView.as_view(
        email_template_name='accounts/password_reset_email.html',
        subject_template_name='accounts/password_reset_subject.txt',
        success_url=reverse_lazy('accounts:password_reset_done'),
        template_name='accounts/password_reset_form.html',
    ), name='password_reset'),
    path('password/reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='accounts/password_reset_done.html'
    ), name='password_reset_done'),

    path('settings/password/', views.password, name='password'),

    path('signup/', views.signup_view, name="signup"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout")
]

articles/urls.py
from django.urls import path, re_path
from . import views

app_name = 'articles'

urlpatterns = [
    path('liking', views.liking, name='liking'),
    path('add_to_view', views.add_to_view, name='add-to-view'),
    path('add_to_favourite', views.add_to_favourite, name='liking'),
    path('favourite-articles', views.favourite_articles, name='favourite-articles'),
    path('report-to-comment', views.report_to_comment, name='report-to-comment'),
    path('report-to-article', views.report_to_article, name='report-to-article'),
    path('follow-to-categories', views.following_to_category, name='follow-to-categories'),
    path('follow-to-users', views.following_to_user, name='follow-to-users'),
    path('', views.article_list, name="list"),
    path('following/', views.list_by_following, name="list-by-following"),
    path('top/', views.list_by_top, name="list-by-top"),
    path('categories/', views.category_list, name="category-list"),
    path('category/<str:slug>', views.articles_by_category, name="articles-by-category"),
    path('new', views.article_create, name="create"),
    re_path('delete-comment/(?P<pk>\\d+)', views.delete_comment, name='delete-comment'),
    re_path('add-comment/(?P<pk>\\d+)', views.add_comment, name='add-comment'),
    re_path('(?P<slug>[\\w-]+)/edit', views.article_edit, name='edit'),
    re_path('(?P<slug>[\\w-]+)/delete', views.article_delete, name='delete'),
    re_path('(?P<slug>[\\w-]+)/$', views.article_detail, name='detail')
]

blogger/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include, re_path
from articles import views as article_views
from accounts import views as accounts_views
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('oauth/', include('social_django.urls', namespace='social')),
    re_path(r'^markdownx/', include('markdownx.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
    re_path('^tags/(?P<tag>[\\w-]+)', article_views.articles_by_tag, name='articles-by-tag'),
    path('', article_views.article_list, name="home"),
    re_path(r'^@(?P<username>.+)$', views.username_detail, name='users-profile'),
    path('profile/', include('profiles.urls')),
    path('search/tags/', article_views.article_tag_search, name='search-tag'),
    path('search/users/', accounts_views.users_search, name='search-users'),
    path('search/', article_views.article_search, name='search'),
)

profiles/urls.py
from django.urls import path, re_path
from . import views

app_name = 'profiles'

urlpatterns = [
    path('', views.profile_detail, name='profile-details'),
    # path('edit', views.update_profile, name='profile-update'),
    path('articles/draft', views.draft_articles, name='draft-articles'),
    path('articles/published', views.published_articles, name='published-articles'),
    path('set-avatar/', views.set_avatar, name='set-avatar')
]

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    avatar = models.ImageField(default=None, blank=True, null=True,
                               upload_to='users_photos/')

    def __str__(self):
        return self.user.username

    def get_username(self):
        return reverse('user-details', args=[str(self.user.username)])

    def snippet(self):
        return self.bio[:25] + '...'


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class SocialNetwork(models.Model):
    title = models.CharField(max_length=63)
    class_name = models.CharField(max_length=31)
    link_to_sn = models.CharField(max_length=63)
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.title


class ConnectToSocialAccount(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    social_network = models.ForeignKey(SocialNetwork, on_delete=models.CASCADE)
    username = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.username} [{self.social_network}]'

profiles/forms.py
from PIL import Image
from django.contrib.auth.models import User
from django import forms
from profiles.models import Profile


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username')
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control-sm'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control-sm'}),
            'email': forms.EmailInput(attrs={'class': 'form-control-sm'}),
            'username': forms.TextInput(attrs={'class': 'form-control-sm'}),
        }


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('bio', 'location', 'birth_date', 'avatar')
        widgets = {
            'bio': forms.Textarea(attrs={'rows': '8', 'style': 'resize: vertical'}),
            'location': forms.TextInput(attrs={'class': 'form-control-sm'}),
            'birth_date': forms.DateInput(attrs={'class': 'form-control-sm'}),
            'avatar': forms.FileInput(attrs={'class': 'file-upload', 'required': False})
        }


class AvatarForm(forms.ModelForm):
    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())

    class Meta:
        model = Profile
        fields = ('avatar', 'x', 'y', 'width', 'height')
        widgets = {
            'avatar': forms.FileInput(attrs={'class': 'file-upload', 'required': False})
        }

    def save(self):
        profile = super(AvatarForm, self).save()
        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')

        image = Image.open(profile.avatar)
        cropped_image = image.crop((x, y, w + x, h + y))
        resized_image = cropped_image.resize((1000, 1000), Image.ANTIALIAS)
        resized_image.save(profile.avatar.path)

        return profile

profiles/views.py
import os

from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.models import User
from django.core import serializers
from django.core.paginator import Paginator
from django.db import transaction
from django.http import HttpResponse
from django.shortcuts import render, redirect
from social_django.models import UserSocialAuth

import json

from articles.models import Article
from profiles.forms import UserForm, ProfileForm, AvatarForm
from profiles.models import Profile, SocialNetwork, ConnectToSocialAccount


@login_required
@transaction.atomic
def profile_detail(request):
    social_networks = SocialNetwork.objects.all()
    social_accounts = ConnectToSocialAccount.objects.filter(user_id=request.user.id)
    # social_accounts = json.loads(serializers.serialize('json', social_accounts))
    try:
        username = User.objects.get(username=request.user.username)
        profile = Profile.objects.get(user__username=username)
    except User.DoesNotExist:
        profile = None
        username = None
    except Profile.DoesNotExist:
        profile = None
    articles = Article.objects.filter(author=username, status='published')
    if request.method == 'POST':
        if '_profile_edit' in request.POST:
            user_form = UserForm(request.POST, instance=request.user)
            profile_form = ProfileForm(request.POST, instance=request.user.profile)
            if user_form.is_valid() and profile_form.is_valid():
                user_form.save()
                profile_form.save()
                messages.success(request, ('Your profile was successfully updated!'))
                return redirect('/profile', username=username)
            else:
                messages.error(request, ('Please correct the error below.'))
        elif '_change_password' in request.POST:
            password_change_form = PasswordChangeForm(request.user, request.POST)
            if password_change_form.is_valid():
                user = password_change_form.save()
                update_session_auth_hash(request, user)
                messages.success(request, ('Your password was successfully changed!'))
                return redirect('/profile', username=username)
            else:
                messages.error(request, ('Please correct the error below.'))
        elif '_social_account' in request.POST:
            socials = [[x[3:], y] for x, y in request.POST.items() if x[0:3] == '_s_']
            for i in socials:
                social = SocialNetwork.objects.filter(title=i[0])
                if social and i[1] != '':
                    ConnectToSocialAccount.objects.update_or_create(user_id=request.user.id,
                                                                    social_network_id=social[0].id,
                                                                    defaults={
                                                                        'username': i[1],
                                                                    })
            return redirect('/profile', username=username)

        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
        password_change_form = PasswordChangeForm(request.user)
        avatar_form = AvatarForm(request.profile.user)
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
        password_change_form = PasswordChangeForm(request.user)
        avatar_form = AvatarForm(instance=request.user.profile)

    user = request.user
    try:
        twitter_login = user.social_auth.get(provider='twitter')
    except UserSocialAuth.DoesNotExist:
        twitter_login = None

    try:
        facebook_login = user.social_auth.get(provider='facebook')
    except UserSocialAuth.DoesNotExist:
        facebook_login = None

    try:
        google_login = user.social_auth.get(provider='google-oauth2')
    except UserSocialAuth.DoesNotExist:
        google_login = None

    can_disconnect = (user.social_auth.count() > 1 or user.has_usable_password())

    return render(request, 'profile/profile_details.html', {
        'user_form': user_form,
        'profile_form': profile_form,
        'password_change_form': password_change_form,
        'avatar_form': avatar_form,
        'avatar': username.profile.avatar,
        'twitter_login': twitter_login,
        'facebook_login': facebook_login,
        'google_login': google_login,
        'can_disconnect': can_disconnect,
        'articles': articles,
        'profile': profile,
        'social_networks': social_networks,
        'social_accounts': social_accounts,
    })


@login_required
def update_profile(request):
    try:
        username = User.objects.get(username=request.user.username)
        profile = Profile.objects.get(user__username=username)
    except User.DoesNotExist:
        profile = None
    articles = Article.objects.filter(author=username, status='published')
    return render(request, 'profile/profile_details.html',
                  {'articles': articles, 'profile': profile})


NUMBER_OF_ARTICLES_PER_PAGE = 10


def draft_articles(request):
    username = request.user.username
    all_articles = Article.objects.filter(author__username=username)
    published = all_articles.filter(status='published')
    draft = all_articles.filter(status='draft')
    paginator = Paginator(draft, NUMBER_OF_ARTICLES_PER_PAGE)
    page = request.GET.get('page')
    articles = paginator.get_page(page)
    return render(request, 'profile/my_articles.html',
                  {'username': request.user, 'articles': articles, 'published_count': len(published),
                   'draft_count': len(draft), 'draft': True})


def published_articles(request):
    username = request.user.username
    all_articles = Article.objects.filter(author__username=username)
    published = all_articles.filter(status='published')
    draft = all_articles.filter(status='draft')
    paginator = Paginator(published, NUMBER_OF_ARTICLES_PER_PAGE)
    page = request.GET.get('page')
    articles = paginator.get_page(page)
    return render(request, 'profile/my_articles.html',
                  {'username': request.user, 'articles': articles, 'published_count': len(published),
                   'draft_count': len(draft), 'published': True})


def set_avatar(request):
    if request.method == "POST":
        old_image = ''
        if request.user.profile.avatar:
            old_image = request.user.profile.avatar.path
        avatar_form = AvatarForm(data=request.POST, files=request.FILES, instance=request.user.profile)
        if avatar_form.is_valid():
            if os.path.exists(old_image):
                os.remove(old_image)
            avatar_form.user_id = request.user.id
            avatar_form.save()
    return redirect('profiles:profile-details')

templates/profile/_edit_profile_data.html
{% load static %}
<form method="post" action="set-avatar/" enctype="multipart/form-data" id="set_avatar">
    {% csrf_token %}
    <div class="avatar-wrapper my-3 mx-auto">
        <div class="h-100 d-flex align-items-center">
            <img class="profile-pic my-auto"
                 src="{% if avatar %} {{ avatar.url }} {% else %} {% static 'images/default-avatar.jpg' %} {% endif %} "
                 alt="img"/>
        </div>
        <div class="upload-button">
            <i class="fa fa-arrow-circle-up" aria-hidden="true"></i>
        </div>
        {{ avatar_form.avatar }}
        {{ avatar_form.x }}
        {{ avatar_form.y }}
        {{ avatar_form.width }}
        {{ avatar_form.height }}
    </div>
    <div class="modal fade" id="modalCrop">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-body p-0">
                    <img src="" id="image" style="max-width: 80%;">
                </div>
                <div class="modal-footer">
                    <div class="btn-group pull-left" role="group">
                        <button type="button" class="btn btn-default js-zoom-in">
                            <span class="glyphicon glyphicon-zoom-in"></span>
                        </button>
                        <button type="button" class="btn btn-default js-zoom-out">
                            <span class="glyphicon glyphicon-zoom-out"></span>
                        </button>
                    </div>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Nevermind</button>
                    <button type="button" class="btn btn-primary js-crop-and-upload" data-dismiss="modal">Crop and
                        upload
                    </button>
                </div>
            </div>
        </div>
    </div>

</form>

<form>
    {% csrf_token %}
    <div class="form-group">
        <div class="d-lg-flex">
            <div class="form-horizontal col-lg-6">
                <div class="form-group">
                    <div class="d-flex justify-content-between mx-2">
                        <label class="col-form-label">{{ user_form.username.label }}: </label>
                        {{ user_form.username }}
                    </div>
                    {{ user_form.username.errors }}
                </div>
                <div class="form-group">
                    <div class="d-flex justify-content-between mx-2">
                        <label class="col-form-label">{{ user_form.first_name.label }}: </label>
                        {{ user_form.first_name }}
                    </div>
                    {{ user_form.first_name.errors }}
                </div>
                <div class="form-group">
                    <div class="d-flex justify-content-between mx-2">
                        <label class="col-form-label">{{ user_form.last_name.label }}: </label>
                        {{ user_form.last_name }}
                    </div>
                    {{ user_form.last_name.errors }}
                </div>
            </div>
            <div class="form-horizontal col-lg-6">
                <div class="form-group">
                    <div class="d-flex justify-content-between mx-2">
                        <label class="col-form-label">{{ user_form.email.label }}: </label>
                        {{ user_form.email }}
                    </div>
                    {{ user_form.email.errors }}
                </div>
                <div class="form-group">
                    <div class="d-flex justify-content-between mx-2">
                        <label class="col-form-label">{{ profile_form.location.label }}: </label>
                        {{ profile_form.location }}
                    </div>
                    {{ profile_form.location.errors }}
                </div>
                <div class="form-group">
                    <div class="d-flex justify-content-between mx-2">
                        <label class="col-form-label">{{ profile_form.birth_date.label }}: </label>
                        {{ profile_form.birth_date }}
                    </div>
                    {{ profile_form.birth_date.errors }}
                </div>
            </div>
        </div>

        <div class="">
            <label class="col-form-label">{{ profile_form.bio.label }}: </label>
            {{ profile_form.bio }}
            {{ profile_form.bio.errors }}
        </div>

    </div>
    <input type="hidden" name="_profile_edit" value="99">
    <button class="btn btn-outline-success btn-default" type="submit">Save changes</button>
</form>

templates/profile/_edit_profile_security.html
<hr>
<div class="d-flex align-items-center">
    {#            <span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur consectetur debitis, dignissimos#}
    {#                doloremque error esse ex facere iste labore laudantium neque non placeat, quia, quod sint sit temporibus#}
    {#                tenetur veniam!#}
    {#            </span>#}
    {#    <a href="{% if can_disconnect %}#}
    {#                    {% url 'accounts:password_change' %}{% else %} {% url 'accounts:password' %}#}
    {#                 {% endif %}"#}
    {#       class="btn btn-primary btn-sm col-2 pl-0 pr-0 h-50">Change#}
    {#        Password</a>#}
    <div class='mx-auto'>
        <h3>Change your Password</h3>
        <form method='post' action='' class="mt-3">
            {% csrf_token %}
            <input type="hidden" name="_change_password" value="31">
            {% for items_form in password_change_form %}
                <div class="d-flex mx-3">
                    <label>{{ items_form.label }}:</label>
                    <div class="ml-auto">
                        {{ items_form }}
                    </div>
                </div>
                {{ items_form.default_error_messages }}
                {{ items_form.errors }}
            {% endfor %}
            <span style='margin-bottom: 12px;'></span>
            <button type="submit" class='mt-3 btn btn-block btn-success'>Save</button>
        </form>
    </div>
</div>
<hr>

templates/profile/_profile_data.html
{% load static categories %}
<div class="mx-lg-4 m-lg-3">
    <div class="d-lg-flex justify-content-between">
        <div class="my-lg-auto mx-lg-1 mx-auto">
            <div class="avatar-wrapper mb-3">
                <img class="profile-pic {% if profile.avatar %} avatar-modal {% endif %}"
                     src="{% if profile.avatar %} {{ profile.avatar.url }} {% else %} {% static 'images/default-avatar.jpg' %} {% endif %}"
                     alt="img"/>
            </div>
            <div class="profile_avatar_modal">
                <div class="big_img">
                    <img class="view_img_full"
                         src="{% if profile.avatar %} {{ profile.avatar.url }} {% else %} {% static 'images/default-avatar.jpg' %} {% endif %}"
                         alt="">
                </div>
                <div class="img_fixvh">
                    <span class="exit_img"><i class="fa fa-close"></i></span>
                </div>
            </div>
            {% if profile.user.username %}
                <p><i class="icon-at"></i><strong>Username</strong>: {{ profile.user.username }} </p>
            {% endif %}
            <div class="d-flex">
                {% if user.username|lower == profile.user.username|lower %}
                    {% if not profile_form %}
                        <a href="{% url 'profiles:profile-details' %}" class="ml-3 mb-3">
                            <button class="btn btn-outline-success btn-default" type="submit">Open profile
                            </button>
                        </a>

                    {% endif %}
                {% else %}
                    <form action="{% url 'articles:follow-to-users' %}" method="post" class="ml-3 mb-3">
                        {% csrf_token %}
                        <input type="hidden" name="user_id" value="{{ profile.user.id }}">
                        {% is_user_followed profile.user.id user.id as is_follow %}
                        {% if not is_follow %}
                            <input type="hidden" name="what" value="follow">
                            <button type="submit" class="btn btn-primary m-auto">Follow</button>
                        {% else %}
                            <input type="hidden" name="what" value="unfollow">
                            <button type="submit" class="btn btn-danger m-auto">UnFollow</button>
                        {% endif %}
                    </form>
                {% endif %}
            </div>
        </div>

        <div class="info mt-lg-3 mx-auto">
            {% if profile.user.first_name %}
                <p>
                    <i class="icon-user"></i><b>Name</b>: {{ profile.user.first_name }} {{ profile.user.last_name }}
                </p>
            {% endif %}
            {% if profile.user.email %}
                <p><i class="icon-mail"></i><b>Email</b>: {{ profile.user.email }}</p>
            {% endif %}
            {% if profile.user.date_joined %}
                <p><i class="icon-calendar"></i><b>Date joined</b>: {{ profile.user.date_joined|date:'F Y' }}
                </p>
            {% endif %}
            {% if profile.location %}
                <p><i class="icon-location"></i><b>Location</b>: {{ profile.location }}</p>
            {% endif %}
            {% if profile.birth_date %}
                <p><i class="icon-calendar-1"></i><b>Birth date</b>: {{ profile.birth_date|date:'d-M Y' }}</p>
            {% endif %}
        </div>
    </div>
    <div class="mx-1">
        {% if profile.bio %}
            <p class=""><i class="icon-info-circled"></i><b>Bio</b>: {{ profile.bio }}</p>
        {% endif %}
    </div>
    <div class="tags-wrap">
        <span class="m-3 tags">
            {% for social_account in social_accounts %}
                <a href="https://{{ social_account.social_network.link_to_sn }}/{{ social_account.username }}"
                   rel="tag">
                    <i class="{{ social_account.social_network.class_name }}"></i>{{ social_account.social_network.title }}
                </a>
            {% endfor %}
        </span>
    </div>
</div>

templates/profile/_socail_networks_form.html
<form action="" class="w-75 m-2" method="post">
    {% csrf_token %}
    {% for items in social_networks %}
        <div class="d-flex  m-3">
            <label>{{ items.title }}: </label>
            <div class="ml-auto">
                https://{{ items.link_to_sn }}/
                <input type="text" name="_s_{{ items.title }}"
                       {% for social_account in social_accounts %}
                {% if social_account.user.id == request.user.id and items.id == social_account.social_network.id %}
                    value="{{ social_account.username }}"
                {% endif %}
                {% endfor %}
                       >
            </div>
        </div>
    {% endfor %}
    <input type="hidden" name="_social_account" value="93">
    <button class="btn btn-outline-success btn-default" type="submit">Save changes</button>
</form>

templates/profile/my_articles.html
{% extends 'base_full_width.html' %}

{% block content %}
    <div class="h4 pb-3">My articles</div>
    <ul class="nav nav-tabs list-style-none">
        <li class="ml-2 nav-item">
            <a class="nav-link {% if draft %}active{% endif %}" href="{% url 'profiles:draft-articles' %}">
                Draft ({{ draft_count }})
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if published %}active{% endif %}" href="{% url 'profiles:published-articles' %}">
                Published ({{ published_count }})
            </a>
        </li>
    </ul>
    <div class="articles">
        {% for article in articles %}
            {% include '_partials/_article_item_minimal.html' %}
        {% endfor %}
    </div>
    {% if articles.has_other_pages %}
        {% include '_partials/pagination.html' %}
    {% endif %}

{% endblock content %}

templates/profile/profile_details.html
{% extends 'base_full_width.html' %}

{% block header %}Profile{% endblock %}
{% block content %}
    {% if profile.user %}
        <div class="d-flex">
            <div class="nav flex-column nav-pills col-2 border-right border-secondary" id="v-pills-tab" role="tablist"
                 aria-orientation="vertical">
                <a class="nav-link active" id="v-pills-profile-tab" data-toggle="pill" href="#v-pills-profile"
                   role="tab"
                   aria-controls="v-pills-profile" aria-selected="true">Profile</a>
                <a class="nav-link" id="v-pills-profile-edit-tab" data-toggle="pill" href="#v-pills-profile-edit"
                   role="tab"
                   aria-controls="v-pills-profile-edit" aria-selected="true">Edit Profile</a>
                <a class="nav-link" id="v-pills-security-tab" data-toggle="pill" href="#v-pills-security" role="tab"
                   aria-controls="v-pills-security" aria-selected="false">Security</a>
                <a class="nav-link" id="v-pills-social-profiles-tab" data-toggle="pill" href="#v-pills-social-profiles"
                   role="tab"
                   aria-controls="v-pills-social-profiles" aria-selected="false">Social profiles</a>
                <a class="nav-link" id="v-pills-settings-tab" data-toggle="pill" href="#v-pills-settings" role="tab"
                   aria-controls="v-pills-settings" aria-selected="false">Settings</a>
            </div>
            <div class="tab-content mx-auto col-8" id="v-pills-tabContent">
                <div class="tab-pane fade show active" id="v-pills-profile" role="tabpanel"
                     aria-labelledby="v-pills-profile-tab">
                    {% include 'profile/_profile_data.html' %}
                </div>
                <div class="tab-pane fade show" id="v-pills-profile-edit" role="tabpanel"
                     aria-labelledby="v-pills-profile-edit-tab">
                    {% include 'profile/_edit_profile_data.html' %}
                </div>
                <div class="tab-pane fade" id="v-pills-security" role="tabpanel" aria-labelledby="v-pills-security-tab">
                    <h4>Security</h4>
                    {% include 'profile/_edit_profile_security.html' %}
                    <h4>Connect account to your social accounts</h4>
                    <div class="d-flex justify-content-around mt-3">{% include '_partials/settings.html' %}</div>
                </div>
                <div class="tab-pane fade" id="v-pills-social-profiles" role="tabpanel"
                     aria-labelledby="v-pills-social-profiles-tab">
                    {% include 'profile/_socail_networks_form.html' %}
                </div>
                <div class="tab-pane fade" id="v-pills-settings" role="tabpanel" aria-labelledby="v-pills-settings-tab">
                    settings
                </div>
            </div>
        </div>

    {% else %}
        <p>No user with given username!</p>
    {% endif %}
    <br>
{% endblock %}

templates/profile/user_details.html
{% extends 'base_sidebar.html' %}

{% block header %}Profile{% endblock %}
{% block content %}
    {% if profile.user %}
        {% include 'profile/_profile_data.html' %}
    {% else %}
        <p>No user with given username!</p>
    {% endif %}
    <br>
{% endblock %}