articles/urls.py
from django.urls import path, re_path
from . import views

app_name = 'articles'

urlpatterns = [
    path('liking', views.liking, name='liking'),
    path('add_to_view', views.add_to_view, name='add-to-view'),
    path('add_to_favourite', views.add_to_favourite, name='liking'),
    path('favourite-articles', views.favourite_articles, name='favourite-articles'),
    path('report-to-comment', views.report_to_comment, name='report-to-comment'),
    path('report-to-article', views.report_to_article, name='report-to-article'),
    path('follow-to-categories', views.following_to_category, name='follow-to-categories'),
    path('follow-to-users', views.following_to_user, name='follow-to-users'),
    path('', views.article_list, name="list"),
    path('following/', views.list_by_following, name="list-by-following"),
    path('top/', views.list_by_top, name="list-by-top"),
    path('categories/', views.category_list, name="category-list"),
    path('category/<str:slug>', views.articles_by_category, name="articles-by-category"),
    path('new', views.article_create, name="create"),
    re_path('delete-comment/(?P<pk>\\d+)', views.delete_comment, name='delete-comment'),
    re_path('add-comment/(?P<pk>\\d+)', views.add_comment, name='add-comment'),
    re_path('(?P<slug>[\\w-]+)/edit', views.article_edit, name='edit'),
    re_path('(?P<slug>[\\w-]+)/delete', views.article_delete, name='delete'),
    re_path('(?P<slug>[\\w-]+)/$', views.article_detail, name='detail')
]

blogger/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include, re_path
from articles import views as article_views
from accounts import views as accounts_views
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('oauth/', include('social_django.urls', namespace='social')),
    re_path(r'^markdownx/', include('markdownx.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
    re_path('^tags/(?P<tag>[\\w-]+)', article_views.articles_by_tag, name='articles-by-tag'),
    path('', article_views.article_list, name="home"),
    re_path(r'^@(?P<username>.+)$', views.username_detail, name='users-profile'),
    path('profile/', include('profiles.urls')),
    path('search/tags/', article_views.article_tag_search, name='search-tag'),
    path('search/users/', accounts_views.users_search, name='search-users'),
    path('search/', article_views.article_search, name='search'),
)

articles/models.py
from django.core.validators import RegexValidator
from django.db import models
from django.contrib.auth.models import User
from django.utils.html import strip_tags
from markdownx.models import MarkdownxField
import re

from markdownx.utils import markdownify

from core.models import TimestampedModel

alphanumeric = RegexValidator(r'^[0-9a-zA-Z\-\s]*$', 'Only alphanumeric characters, hyphen are allowed.')


class Tag(TimestampedModel):
    title = models.CharField(max_length=50, unique=True, validators=[alphanumeric])

    def __str__(self):
        return self.title.lower().replace(' ', '-')


class Article(TimestampedModel):
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    body = MarkdownxField()
    tag = models.ManyToManyField(Tag, related_name="articles")
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    status = models.CharField(max_length=25,
                              choices=(('draft', 'DRAFT'), ('inreview', 'INREVIEW'), ('published', 'PUBLISHED')),
                              default='draft')
    category = models.ForeignKey('Category', on_delete=models.CASCADE, default=None)
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title

    @property
    def formatted_markdown(self):
        return strip_tags(markdownify(self.body))

    def snippet(self):
        return self.formatted_markdown[:150].replace('\n', ' ') + '...'

    def snippet_large(self):
        return self.formatted_markdown[:350].replace('\n', ' ') + '...'

    def time_of_read(self):
        t1 = len(self.formatted_markdown.replace('\n', '')) / 1500
        t2 = len([m.start() for m in re.finditer(r"(?:!\[(.*?)\]\((.*?)\))", self.body)])
        the_sum = t1 + t2
        n = int(the_sum * 10) % 10
        if the_sum < 1:
            result = '1'
        else:
            if n >= 3:
                result = str(int(the_sum) + 1)
            else:
                result = str(the_sum)
        return result + ' min'

    def get_comments(self):
        return self.comment_set.filter(parent__isnull=True)

    def count_of_likes(self):
        return LikeOfArticle.objects.filter(article_id=self.id).count()

    def count_of_comments(self):
        return Comment.objects.filter(article_id=self.id).exclude(status='deleted').count()

    def count_of_favourites(self):
        return FavouriteArticles.objects.filter(article_id=self.id).count()

    def count_of_views(self):
        return self.views


class Comment(TimestampedModel):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField(max_length=5000)
    parent = models.ForeignKey('self', on_delete=models.SET_NULL, blank=True, null=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=25,
                              choices=(('active', 'ACTIVE'), ('deleted', 'DELETED')),
                              default='active')

    def __str__(self):
        return self.content[0:200] + '[{}]'.format(self.id)


class Category(models.Model):
    title = models.CharField(max_length=25)
    description = models.TextField(blank=True, null=True)
    slug = models.SlugField(unique=True)
    menu_position = models.PositiveSmallIntegerField(default=0)  # if 0, not position. Status = False
    image = models.ImageField(upload_to='categories/', blank=True, null=True)

    def __str__(self):
        return f'{self.title_uz} [{self.id}]'

    @staticmethod
    def get_active_categories():
        return Category.objects.filter(article__isnull=False)

    def get_count_articles(self):
        return Article.objects.filter(category_id=self.id, status='published').count()


class LikeOfArticle(models.Model):
    article = models.ForeignKey('Article', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.article.title}-{self.user.username} [{self.id}]'


class FavouriteArticles(models.Model):
    article = models.OneToOneField('Article', on_delete=models.CASCADE)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.article.title}-{self.user.username} [{self.id}]'

    def save(self, *args, **kwargs):
        if FavouriteArticles.objects.filter(article=self.article, user=self.user).count() == 0:
            super(FavouriteArticles, self).save(*args, **kwargs)
        else:
            pass


class ReportToArticle(models.Model):
    class TypeOfReport(models.IntegerChoices):
        report_1 = 1
        report_2 = 2
        report_3 = 3
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    from_user = models.ForeignKey(User, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    type_of_report = models.IntegerField(choices=TypeOfReport.choices, default=1, blank=True, null=True)
    extra_comment = models.CharField(max_length=255)


class ReportToComment(models.Model):
    class TypeOfReport(models.Choices):
        This_is_spam = 1
        This_reporting = 2
        This_18_plus = 3
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    from_user = models.ForeignKey(User, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    type_of_report = models.IntegerField(choices=TypeOfReport.choices, default=1, blank=True, null=True)
    extra_comment = models.CharField(max_length=255, blank=True, null=True)

articles/forms.py
from django import forms
from markdownx.fields import MarkdownxFormField

from . import models
from django.core.validators import RegexValidator

alphanumeric = RegexValidator(r'^([0-9a-zA-Z\-\s]*[,]){,4}[0-9a-zA-Z\-\s]*$',
                              'Only alphanumeric characters, hyphen are allowed. Maximum 5 tags can be used')


class CreateArticle(forms.ModelForm):
    tag = forms.CharField(max_length=100, validators=[alphanumeric], help_text='(Separate tags with comma)')

    class Meta:
        model = models.Article
        fields = ['title', 'body', 'slug', 'category', 'tag']


class EditArticle(forms.ModelForm):
    tag = forms.CharField(max_length=100, validators=[alphanumeric], help_text='(Separate tags with comma)')
    body = MarkdownxFormField()

    class Meta:
        model = models.Article
        fields = ['title', 'body', 'slug', 'tag']


class CommentForms(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields = ['content', ]

    content = forms.CharField(
        widget=forms.Textarea(attrs={'required': True, 'style': 'resize: vertical; min-height: 160px; height: 200px'}),
        error_messages='', label='Content')

templates/articles/article_create.html
{% extends 'base_full_width.html' %}

{% block content %}
    <div class="create-article">
        <h2>Create article</h2>
        <form class="site-form pt-3" action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <input type="submit" name="" value="Create">
        </form>
        {{ form.media }}
    </div>
{% endblock %}

templates/articles/article_detail.html
{% extends 'base_single.html' %}
{% load social_share %}

{% block header %}{{ article.title |capfirst }}{% endblock %}

{% block content %}
    <p>{{ body|safe }}</p>
{% endblock %}
{% block bottom %}
    <div class="d-flex col-10 mx-auto align-items-center">

        <div class="mr-auto like-icon">
            <span {% if user.is_authenticated %}onclick="liking(event)"{% else %} data-toggle="modal"
                  data-target="#modalLRForm"{% endif %}>
                <i class="icon-heart{% if liked %}-fill{% endif %}" style="font-size: 35px; cursor: pointer"
                   data-original-title="Like" title data-toggle="tooltip" data-placement="top"></i>
            </span>
            <span id="count_of_likes">
                {% if count_of_likes %}x{{ count_of_likes }}{% endif %}
            </span>
            <span {% if user.is_authenticated %}data-target="#report_article-{{ article.id }}"{% else %}data-target="#modalLRForm"{% endif %}
                  data-toggle="modal">
                <i class="icon-attention ml-1" style="font-size: 35px; cursor: pointer"
                data-original-title="Report" title data-toggle="tooltip" data-placement="top"></i>
            </span>
        </div>

        <div class="dropleft" data-original-title="Share" title data-toggle="tooltip" data-placement="top">
            <i class="icon-share mr-2" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false"
               style="font-size: 35px; cursor: pointer"></i>
            <div class="dropdown-menu">
                <div class="dropdown-item">{% post_to_facebook request.build_absolute_uri '<i class="icon-facebook text-primary"></i>Facebook'|safe %}</div>
                <div class="dropdown-item">{% post_to_twitter article.title request.build_absolute_uri '<i class="icon-twitter text-primary"></i>Twitter'|safe %}</div>
                <div class="dropdown-item">{% post_to_telegram article.title request.build_absolute_uri '<i class="icon-telegram text-info"></i>Telegram'|safe %}</div>
                <div class="dropdown-item">{% post_to_whatsapp request.build_absolute_uri '<i class="icon-whatsapp text-success"></i>WhatsApp'|safe %}</div>
                <div class="dropdown-item">{% send_email "Post" "{{article.title}}" request.build_absolute_uri '<i class="icon-mail text-danger"></i>To Email'|safe %}</div>
                <div class="dropdown-divider"></div>
                <div class="dropdown-item" onclick="copyToClipboard('{{ request.build_absolute_uri }}')">
                    <a href="javascript:void(0);">
                        <i class="icon-link text-muted"></i>Copy Link
                    </a>
                </div>
            </div>
        </div>
        <span {% if user.is_authenticated %}onclick="addToFavourite(event)"{% else %}data-toggle="modal"
              data-target="#modalLRForm"{% endif %}>

        <i class="icon-bookmark{% if not favourite %}-empty{% endif %} m-0"
           style="font-size: 35px; cursor: pointer" data-original-title="Favourite" title data-toggle="tooltip"
           data-placement="top"></i>
            </span>
    </div>
    {% if article.tag %}
        <div class="entry-bottom">
            <div class="tags-wrap heading">
                <span class="tags">
                    {% for tags in article.tag.all|dictsort:"title" %}
                        <a href="{% url 'articles-by-tag' tags %}" class="px-2 py-1" rel="tag"><i
                                class="icon-tag-1"></i>{{ tags }}</a>
                    {% endfor %}
                </span>
            </div>
        </div>
    {% endif %}
    {% include '_partials/_modal_signin_signup.html' with form_login=form_login form_signup=form_signup %}
    {% include '_partials/_modal_report_article.html' with id_modal=article.id reports=article_reports %}
{% endblock %}

templates/articles/article_edit.html
{% extends 'base_full_width.html' %}

{% block content %}
    <div class="create-article">
        <h2>Edit article</h2>
        <form class="site-form pt-3" action="{% url 'articles:edit' article.slug %}" method="post"
              enctype="multipart/form-data">
            {% csrf_token %}
            Title:
            {{ form.title }}
            Body:
            {{ form.body }}
            Slug:
            {{ form.slug }}
            Tags:
            <input type="text" name="tag" value="{{ tags }}" maxlength="100" required="" id="id_tag">
            <input type="submit" name="" value="Save">
        </form>
        {{ form.media }}
    </div>
{% endblock %}

templates/articles/article_list.html
{% extends 'base_sidebar.html' %}

{% block header %}Bas bet{% endblock %}

{% block content %}
    <ul class="nav nav-tabs list-style-none my-2">
        <li class="ml-2 nav-item">
            <a class="nav-link {% if by_date %}active{% endif %}"
               href="{% url 'articles:list' %}">By date</a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if by_following %}active{% endif %}"
               href="{% url 'articles:list-by-following' %}">By following</a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if by_top %}active{% endif %}"
               href="{% url 'articles:list-by-top' %}">Top of week</a>
        </li>
    </ul>

    <div class="articles items">
        {% for article in articles %}
            {% include '_partials/_article_item.html' %}
        {% endfor %}

        {% if not articles and by_following %}

            <p class="m-3 h5">
                {% if user.is_authenticated %}
                    You are not subscribed to any category or author
                {% else %}
                    You are not logged in
                {% endif %}
            </p>
        {% endif %}
    </div>
    {% if articles.has_other_pages %}
        {% include '_partials/pagination.html' %}
    {% endif %}
{% endblock %}

templates/articles/articles_by_category.html
{% extends 'base_sidebar.html' %}

{% block header %}
    Articles in category "{{ category.title|capfirst }}"
{% endblock %}

{% block content %}
    <div class="articles">
        {% for article in articles %}
            {% include '_partials/_article_item.html' %}
        {% endfor %}
        {% if articles.has_other_pages %}
            {% include '_partials/pagination.html' %}
        {% endif %}
    </div>
{% endblock %}

templates/articles/articles_by_tag.html
{% extends 'base_sidebar.html' %}

{% block header %}
    Tagged in  "{{ tag|capfirst }}"
{% endblock %}

{% block content %}
    <div class="articles">
        {% for article in articles %}
            {% include '_partials/_article_item.html' %}
        {% endfor %}
        {% if articles.has_other_pages %}
            {% include '_partials/pagination.html' %}
        {% endif %}
    </div>
{% endblock %}

templates/articles/category_list.html
{% extends 'base_sidebar.html' %}

{% block header %}Categories{% endblock %}

{% block content %}
    <div class="articles">
        {% for category in categories %}
            {% include '_partials/_category_item.html' %}
        {% endfor %}
    </div>
    {% if categories.has_other_pages %}
        {% with categories as articles %}
            {% include '_partials/pagination.html' %}
        {% endwith %}
    {% endif %}
{% endblock %}

templates/articles/favourite_articles.html
{% extends 'base_empty.html' %}

{% block content %}
    {% for article in articles %}
        {% include '_partials/_article_item.html' %}
    {% endfor %}
{% endblock %}