accounts/urls.py
from django.urls import path, reverse_lazy, re_path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'accounts'

urlpatterns = [
    path('password/change/', auth_views.PasswordChangeView.as_view(
        success_url=reverse_lazy('accounts:password_change_done'),
        template_name='accounts/password_change_form.html',
    ),
        name='password_change'),
    path('password/change/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='accounts/password_change_done.html',
    ), name='password_change_done'),
    path('password/reset/complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='accounts/password_reset_complete.html'
    ),
         name='password_reset_complete'),
    re_path(r'^password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,40})/$',
            auth_views.PasswordResetConfirmView.as_view(
                template_name='accounts/password_reset_confirm.html',
                success_url=reverse_lazy('accounts:password_reset_complete')
            ),
            name='password_reset_confirm'),
    path('password/reset/', auth_views.PasswordResetView.as_view(
        email_template_name='accounts/password_reset_email.html',
        subject_template_name='accounts/password_reset_subject.txt',
        success_url=reverse_lazy('accounts:password_reset_done'),
        template_name='accounts/password_reset_form.html',
    ), name='password_reset'),
    path('password/reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='accounts/password_reset_done.html'
    ), name='password_reset_done'),

    path('settings/password/', views.password, name='password'),

    path('signup/', views.signup_view, name="signup"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout")
]

articles/urls.py
from django.urls import path, re_path
from . import views

app_name = 'articles'

urlpatterns = [
    path('liking', views.liking, name='liking'),
    path('add_to_view', views.add_to_view, name='add-to-view'),
    path('add_to_favourite', views.add_to_favourite, name='liking'),
    path('favourite-articles', views.favourite_articles, name='favourite-articles'),
    path('report-to-comment', views.report_to_comment, name='report-to-comment'),
    path('report-to-article', views.report_to_article, name='report-to-article'),
    path('follow-to-categories', views.following_to_category, name='follow-to-categories'),
    path('follow-to-users', views.following_to_user, name='follow-to-users'),
    path('', views.article_list, name="list"),
    path('following/', views.list_by_following, name="list-by-following"),
    path('top/', views.list_by_top, name="list-by-top"),
    path('categories/', views.category_list, name="category-list"),
    path('category/<str:slug>', views.articles_by_category, name="articles-by-category"),
    path('new', views.article_create, name="create"),
    re_path('delete-comment/(?P<pk>\\d+)', views.delete_comment, name='delete-comment'),
    re_path('add-comment/(?P<pk>\\d+)', views.add_comment, name='add-comment'),
    re_path('(?P<slug>[\\w-]+)/edit', views.article_edit, name='edit'),
    re_path('(?P<slug>[\\w-]+)/delete', views.article_delete, name='delete'),
    re_path('(?P<slug>[\\w-]+)/$', views.article_detail, name='detail')
]

blogger/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include, re_path
from articles import views as article_views
from accounts import views as accounts_views
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('oauth/', include('social_django.urls', namespace='social')),
    re_path(r'^markdownx/', include('markdownx.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
    re_path('^tags/(?P<tag>[\\w-]+)', article_views.articles_by_tag, name='articles-by-tag'),
    path('', article_views.article_list, name="home"),
    re_path(r'^@(?P<username>.+)$', views.username_detail, name='users-profile'),
    path('profile/', include('profiles.urls')),
    path('search/tags/', article_views.article_tag_search, name='search-tag'),
    path('search/users/', accounts_views.users_search, name='search-users'),
    path('search/', article_views.article_search, name='search'),
)

profiles/urls.py
from django.urls import path, re_path
from . import views

app_name = 'profiles'

urlpatterns = [
    path('', views.profile_detail, name='profile-details'),
    # path('edit', views.update_profile, name='profile-update'),
    path('articles/draft', views.draft_articles, name='draft-articles'),
    path('articles/published', views.published_articles, name='published-articles'),
    path('set-avatar/', views.set_avatar, name='set-avatar')
]

profiles/forms.py
from PIL import Image
from django.contrib.auth.models import User
from django import forms
from profiles.models import Profile


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username')
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control-sm'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control-sm'}),
            'email': forms.EmailInput(attrs={'class': 'form-control-sm'}),
            'username': forms.TextInput(attrs={'class': 'form-control-sm'}),
        }


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('bio', 'location', 'birth_date', 'avatar')
        widgets = {
            'bio': forms.Textarea(attrs={'rows': '8', 'style': 'resize: vertical'}),
            'location': forms.TextInput(attrs={'class': 'form-control-sm'}),
            'birth_date': forms.DateInput(attrs={'class': 'form-control-sm'}),
            'avatar': forms.FileInput(attrs={'class': 'file-upload', 'required': False})
        }


class AvatarForm(forms.ModelForm):
    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())

    class Meta:
        model = Profile
        fields = ('avatar', 'x', 'y', 'width', 'height')
        widgets = {
            'avatar': forms.FileInput(attrs={'class': 'file-upload', 'required': False})
        }

    def save(self):
        profile = super(AvatarForm, self).save()
        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')

        image = Image.open(profile.avatar)
        cropped_image = image.crop((x, y, w + x, h + y))
        resized_image = cropped_image.resize((1000, 1000), Image.ANTIALIAS)
        resized_image.save(profile.avatar.path)

        return profile

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>blogger.com {% block title %} {% endblock %}</title>
    <!--favincon-->
    <link rel="icon" type="image/png" sizes="32x32" href="/static/images/favicon/favicon-32x32.png">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/static/images/favicon/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">

    <!-- Bootstrap, Font Awesome, Aminate, Owl Carausel, Normalize CSS -->
    <link href="/static/css/bootstrap.css" rel="stylesheet">
    <link href="/static/css/owl.carousel.min.css" rel="stylesheet">
    <link href="/static/css/owl.theme.default.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Material Design Bootstrap -->
    {#    <link href="/static/css/mdb.min.css" rel="stylesheet">#}

    <!-- Site CSS -->
    <link href="/static/css/style.css" rel="stylesheet">
    <link href="/static/css/widgets.css" rel="stylesheet">
    <link href="/static/css/color-default.css" rel="stylesheet">
    <link href="/static/css/responsive.css" rel="stylesheet">
    {#    <link rel="stylesheet" type="text/css" href="/static/css/media.css">#}
    {#    <link rel="stylesheet" type="text/css" href="/static/css/font-awesome.css">#}

    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Cabin:400,700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=B612+Mono&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Serif:ital,wght@0,400;0,700;1,400;1,700&display=swap"
          rel="stylesheet">


    <!-- Icons fonts-->
    <link href="/static/css/fontello.css" rel="stylesheet">
</head>
<body class="archive">
<div class="top-scroll-bar"></div>
<!--Mobile navigation-->
<div class="sticky-header fixed d-lg-none d-md-block">
    <div class="text-right">
        <div class="container mobile-menu-fixed pr-5">
            <h1 class="logo-small navbar-brand"><a href="index.html" class="logo">Merinda</a></h1>

            <a class="author-avatar" href="#"><img src="/static/images/author-avata-1.jpg" alt=""></a>

            <ul class="social-network heading navbar-nav d-lg-flex align-items-center">
                <li><a href="#"><i class="icon-facebook"></i></a></li>
            </ul>

            <a href="javascript:void(0)" class="menu-toggle-icon">
                <span class="lines"></span>
            </a>
        </div>
    </div>

    <div class="mobi-menu">
        <div class="mobi-menu__logo">
            <h1 class="logo navbar-brand"><a href="index.html" class="logo">Merinda</a></h1>
        </div>
        <form action="#" method="get" class="menu-search-form d-lg-flex">
            <input type="text" class="search_field" placeholder="Search..." value="" name="s">
        </form>
        <nav>
            <ul>
                <li class="current-menu-item"><a href="index.html">Home</a></li>
                <li class="menu-item-has-children"><a href="categories.html">Categories</a>
                    <ul class="sub-menu">
                        <li><a href="categories.html">Politics</a></li>
                        <li><a href="categories.html">Health</a></li>
                        <li><a href="categories.html">Design</a></li>
                    </ul>
                </li>
                <li><a href="typography.html">Typography</a></li>
                <li><a href="categories.html">Politics</a></li>
                <li><a href="categories.html">Health</a></li>
                <li><a href="contact.html">Contact</a></li>
            </ul>
        </nav>
    </div>
</div>
<!--Mobile navigation-->
<div id="wrapper">
    <header id="header" class="d-lg-block d-none">

        {% include '_partials/header.html' %}

        {% include '_partials/categories.html' %}

    </header>
    <main id="content">

        {% block root_content %}
        {% endblock %}

    </main>

    {% include '_partials/footer.html' %}

</div> <!--#wrapper-->

<a href="#" class="back-to-top heading"><i class="icon-left-open-big"></i><span class="d-lg-inline d-md-none">Top</span></a>

<!--Scripts-->
<script src="/static/js/jquery.min.js"></script>
{#<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="#}
{#        crossorigin="anonymous"></script>#}
<script type="text/javascript" src="/static/js/popper.min.js"></script>
<script src="/static/js/bootstrap.js"></script>
<script src="/static/js/jquery-scrolltofixed-min.js"></script>
{#<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>#}
<script src="/static/js/theia-sticky-sidebar.js"></script>
<!-- Bootstrap tooltips -->
<!-- MDB core JavaScript -->
{#<script type="text/javascript" src="/static/js/mdb.min.js"></script>#}
<script type="text/javascript" src="/static/js/jquery.lazy.min.js"></script>
<script type="text/javascript" src="/static/js/owl.carousel.min.js"></script>
<script src="/static/js/scripts.js"></script>
{% block jslibs %}
{% endblock %}
</body>
</html>

templates/base_empty.html
{% extends 'base.html' %}

{% block root_content %}
<div class="container">
    {% block content %}
    {% endblock %}
</div> <!--container-->
{% endblock %}

templates/base_full_width.html
{% extends 'base.html' %}

{% block root_content %}
    <div class="container">
        <article class="entry-wraper full-width mb-5">
            <div class="entry-content">
                <h4 class="spanborder">
                    <span>{% block header %} {% endblock %}</span>
                </h4>
                {% block content %}
                {% endblock %}
            </div>
        </article> <!--entry-content-->

    </div> <!--container-->
{% endblock %}

{% block jslibs %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/cropper/4.1.0/cropper.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cropper/4.1.0/cropper.min.css">
    <script>
        var $image_1 = $('.profile-pic')
        var $image = $("#image");
        var cropBoxData;
        var canvasData;
        $("#modalCrop").on("shown.bs.modal", function () {
            $image.cropper({
                viewMode: 1,
                aspectRatio: 1 / 1,
                minCropBoxWidth: 200,
                minCropBoxHeight: 200,
                ready: function () {
                    $image.cropper("setCanvasData", canvasData);
                    $image.cropper("setCropBoxData", cropBoxData);
                }
            });
        }).on("hidden.bs.modal", function () {
            cropBoxData = $image.cropper("getCropBoxData");
            canvasData = $image.cropper("getCanvasData");
            $image.cropper("destroy");
        });

        // Enable zoom in button
        $(".js-zoom-in").click(function () {
            $image.cropper("zoom", 0.1);
        });

        // Enable zoom out button
        $(".js-zoom-out").click(function () {
            $image.cropper("zoom", -0.1);
        });
        /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
        $(".js-crop-and-upload").click(function () {
            var cropData = $image.cropper("getData");
            $("#id_x").val(cropData["x"]);
            $("#id_y").val(cropData["y"]);
            $("#id_height").val(cropData["height"]);
            $("#id_width").val(cropData["width"]);
            $("#set_avatar").submit();
        });
    </script>
    <script>
        $('textarea#id_body').each(function () {
            this.setAttribute('style', 'height:' + (this.scrollHeight) + 'px;overflow-y:hidden;');
        }).on('input', function () {
            this.style.height = 'auto';
            this.style.height = (this.scrollHeight) + 'px';
        });
    </script>
{% endblock %}

templates/base_layout.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <header>
    <nav class="navbar navbar-expand-lg navbar-light font-weight-bold">
      <div class="container">
        <a class="navbar-brand font-weight-bold" href="{% url 'home' %}">Blogqiziq</a>
      </div>
      <ul style="display: inline;">
        {% if user.is_authenticated %}
        <li>
          <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
            {% csrf_token %}
            <button type="submit">Logout</button>
          </form>
        </li>
        <li><a href="{% url 'articles:create' %}">New Article</a></li>
        <li><a href="{% url 'profiles:profile-details' %}">Profile</a></li>
        {% else %}
          <li><a href="{% url 'accounts:login' %}">Login</a></li>
          <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
        {% endif %}
      </ul>
    </nav>
  </header>
  <body>
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

templates/base_sidebar.html
{% extends 'base.html' %}

{% block root_content %}
<div class="content-widget">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <h4 class="spanborder">
                    <span>{% block header %} {% endblock %}</span>
                </h4>

                {% block content %}
                {% endblock %}
<!--                    {% include '_partials/sample_articles.html' %}-->
            </div> <!--col-md-8-->

            {% include '_partials/sidebar.html' %}

        </div>
    </div> <!--content-widget-->
</div>
{% endblock %}

templates/homepage.html
{% extends 'base_sidebar.html' %}

{% block content %}
  <h1>Homepage</h1>
{% endblock %}

templates/search.html
{% extends 'base_full_width.html' %}

{% block content %}
    <div>
        <form class="d-flex"
              action="{% if is_articles %} {% url 'search' %} {% elif is_users %} {% url 'search-users' %} {% else %} {% url 'search-tag' %} {% endif %}">
            <input type="text" class="search mb-4" value="{{ query }}" placeholder="{{ query }}"
                   name="q">
        </form>
    </div>
    <ul class="nav nav-tabs list-style-none">
        <li class="ml-2 nav-item">
            <a class="nav-link {% if is_articles %}active{% endif %}"
               href="{% url 'search' %}?q={{ query }}">Articles</a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if is_users %}active{% endif %}"
               href="{% url 'search-users' %}?q={{ query }}">Users</a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if is_tags %}active{% endif %}"
               href="{% url 'search-tag' %}?q={{ query }}">Tags</a>
        </li>
    </ul>
    <div class="items mx-3">
        {% if is_articles %}
            <div class="articles mt-4">
                {% for article in articles %}
                    {% include '_partials/_article_item_minimal.html' %}
                {% endfor %}
            </div>
            {% if  not articles %}
                <b class="ml-3">No articles found!</b>
            {% endif %}
        {% elif is_users %}
            <div class="fa-user mt-4">
                {% for user in users %}
                    {% include '_partials/_user_item.html' %}
                {% endfor %}
            </div>
            {% if not users %}
                <b class="ml-3">No users found!</b>
            {% endif %}
        {% elif is_tags %}
            <div class="tags-wrap">
                {% for tag in tags %}
                    <span class="mb-2">
                    <a href="{% url 'articles-by-tag' tag %}" rel="tag">{{ tag }}</a>
                </span>
                {% endfor %}
            </div>
            {% if not tags %}
                <b class="ml-3">No tags found!</b>
            {% endif %}
        {% endif %}
        {% if articles.has_other_pages or tags.has_other_pages or users.has_other_pages %}
            {% include '_partials/pagination.html' %}
        {% endif %}
    </div>
{% endblock content %}